tst_rast: tst_rast.o raster.o rast_asm.o rooms.o bitmaps.o render.o
	cc68x -g tst_rast.o raster.o rast_asm.o bitmaps.o rooms.o render.o -o tst_rast

tst_rast.o: tst_rast.c 
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

bitmaps.o:	bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c
	
rooms.o:	rooms.c rooms.h
	cc68x -g -c rooms.c
	
render.o: render.c render.h
	cc68x -g -c render.c